"""Regenerate a human-readable summary of a ledger (machine-written, committable).

Reads an append-only ledger and writes a `summary.md` next to it: the current
leaderboard (most favorable first), coverage counts, and the methods in play.
This is the auto-published artifact the autopilot commits every tick; the curated
narrative stays in the top-level JOURNAL.md.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cheiron.ledger import Ledger  # noqa: E402


def build_summary(ledger_path: Path) -> str:
    ledger = Ledger(ledger_path)
    latest = list(ledger.latest_by_spec().values())
    all_records = ledger.read_all()

    usable = [r for r in latest
              if r.get("fitness") and r["fitness"].get("valid")
              and r["fitness"].get("fitness") is not None]
    usable.sort(key=lambda r: r["fitness"]["fitness"], reverse=True)

    favorable = [r for r in usable if r["fitness"].get("favorable")]
    unfavorable = [r for r in usable if r["fitness"].get("favorable") is False]
    failed = [r for r in latest if not (r.get("fitness") and r["fitness"].get("valid"))]
    methods = sorted({(r.get("measurement") or {}).get("method")
                      for r in usable if r.get("measurement")})

    lines = [
        "# M0 — hydrogen abstraction: ledger summary",
        "",
        "_Auto-generated by `scripts/summarize.py`. Do not edit by hand; the",
        "append-only ledger (`ledger.jsonl`) is the source of truth._",
        "",
        f"- distinct candidates: **{len(latest)}**  "
        f"(ledger rows incl. supersedes: {len(all_records)})",
        f"- usable measurements: **{len(usable)}**  "
        f"(favorable {len(favorable)}, unfavorable {len(unfavorable)})",
        f"- unusable / build failures: **{len(failed)}**",
        f"- arbiter methods: {', '.join(m for m in methods if m) or 'n/a'}",
        "",
        "## Leaderboard (most favorable first)",
        "",
        "| candidate | tool | workpiece | site | ΔE (kcal/mol) | favorable |",
        "|-----------|------|-----------|------|--------------:|:---------:|",
    ]
    for r in usable:
        spec, fit = r["spec"], r["fitness"]
        lines.append(
            f"| {spec['id']} | {spec['tool']['id']} | {spec['workpiece']['id']} "
            f"| {spec['workpiece']['abstract_site']} "
            f"| {fit['reaction_energy_kcal']:+.1f} "
            f"| {'yes' if fit['favorable'] else 'no'} |"
        )

    if failed:
        lines += ["", "## Unusable / failed", ""]
        for r in failed:
            note = (r.get("fitness") or {}).get("note") or \
                   (r.get("build") or {}).get("error") or "unknown"
            lines.append(f"- `{r['spec']['id']}` — {note}")

    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    ledger_path = Path(argv[0]) if argv else \
        ROOT / "experiments/m0_hydrogen_abstraction/results/ledger.jsonl"
    out = ledger_path.parent / "summary.md"
    out.write_text(build_summary(ledger_path), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
