"""Regenerate a human-readable summary of a ledger (machine-written, committable).

Reads an append-only ledger and writes a `summary.md` next to it: the current
leaderboard (most favorable first), coverage counts, and the methods in play.
This is the auto-published artifact the autopilot commits every tick; the curated
narrative stays in the top-level JOURNAL.md.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cheiron.ledger import Ledger  # noqa: E402
from cheiron.score import FEASIBLE_BARRIER_KCAL  # noqa: E402
from cheiron.selectivity import site_comparisons  # noqa: E402


def load_barriers(scans_path: Path) -> dict[str, float]:
    """Latest usable relaxed-scan barrier per spec id (later records supersede,
    so corrections appended to the scan file win automatically)."""
    import json

    barriers: dict[str, float] = {}
    if not scans_path.exists():
        return barriers
    with scans_path.open(encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            r = json.loads(line)
            if (
                r.get("kind") == "relaxed_approach_scan"
                and r.get("ok")
                and r.get("barrier_kcal") is not None
            ):
                # annotate non-PBE barriers so mixed methods stay distinguishable
                method = r.get("method", "")
                tag = "" if "/PBE/" in method else " (" + method.split("/")[1] + ")"
                barriers[r["spec_id"]] = (r["barrier_kcal"], tag)
    return barriers


def build_summary(ledger_path: Path) -> str:
    ledger = Ledger(ledger_path)
    latest = list(ledger.latest_by_spec().values())
    all_records = ledger.read_all()
    barriers = load_barriers(ledger_path.parent / "scans.jsonl")

    usable = [r for r in latest
              if r.get("fitness") and r["fitness"].get("valid")
              and r["fitness"].get("fitness") is not None]
    usable.sort(key=lambda r: r["fitness"]["fitness"], reverse=True)

    favorable = [r for r in usable if r["fitness"].get("favorable")]
    unfavorable = [r for r in usable if r["fitness"].get("favorable") is False]
    failed = [r for r in latest if not (r.get("fitness") and r["fitness"].get("valid"))]
    methods = sorted({(r.get("measurement") or {}).get("method")
                      for r in usable if r.get("measurement")})

    lines = [
        "# M0 — hydrogen abstraction: ledger summary",
        "",
        "_Auto-generated by `scripts/summarize.py`. Do not edit by hand; the",
        "append-only ledger (`ledger.jsonl`) is the source of truth._",
        "",
        f"- distinct candidates: **{len(latest)}**  "
        f"(ledger rows incl. supersedes: {len(all_records)})",
        f"- usable measurements: **{len(usable)}**  "
        f"(favorable {len(favorable)}, unfavorable {len(unfavorable)})",
        f"- unusable / build failures: **{len(failed)}**",
        f"- arbiter methods: {', '.join(m for m in methods if m) or 'n/a'}",
        "",
        "## Leaderboard (most favorable first)",
        "",
        "Barrier = relaxed approach scan (M1), profile max vs separated",
        f"fragments; feasible gate at {FEASIBLE_BARRIER_KCAL:.0f} kcal/mol. "
        "'—' = not yet scanned.",
        "",
        "| candidate | tool | workpiece | site | ΔE (kcal/mol) | favorable | barrier (kcal/mol) | feasible |",
        "|-----------|------|-----------|------|--------------:|:---------:|-------------------:|:--------:|",
    ]
    for r in usable:
        spec, fit = r["spec"], r["fitness"]
        entry = barriers.get(spec["id"])
        barrier = None if entry is None else entry[0]
        barrier_cell = "—" if entry is None else f"{barrier:.1f}{entry[1]}"
        feasible_cell = (
            "—" if barrier is None
            else ("yes" if barrier <= FEASIBLE_BARRIER_KCAL else "no")
        )
        lines.append(
            f"| {spec['id']} | {spec['tool']['id']} | {spec['workpiece']['id']} "
            f"| {spec['workpiece']['abstract_site']} "
            f"| {fit['reaction_energy_kcal']:+.1f} "
            f"| {'yes' if fit['favorable'] else 'no'} "
            f"| {barrier_cell} | {feasible_cell} |"
        )

    comparisons = site_comparisons(ledger.latest_by_spec())
    if comparisons:
        lines += [
            "",
            "## Site selectivity (M2, thermodynamic)",
            "",
            "ΔΔE margin between the preferred and runner-up C–H site of the",
            "same molecule under the same tool. Kinetic (barrier) margins are",
            "the sharper question and come from per-site approach scans.",
            "",
            "| tool | molecule | preferred site | margin (kcal/mol) |",
            "|------|----------|----------------|------------------:|",
        ]
        for c in comparisons:
            lines.append(
                f"| {c.tool_id} | {c.molecule} | {c.preferred_site} "
                f"| {c.margin_kcal:.2f} |"
            )

    if failed:
        lines += ["", "## Unusable / failed", ""]
        for r in failed:
            note = (r.get("fitness") or {}).get("note") or \
                   (r.get("build") or {}).get("error") or "unknown"
            lines.append(f"- `{r['spec']['id']}` — {note}")

    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    ledger_path = Path(argv[0]) if argv else \
        ROOT / "experiments/m0_hydrogen_abstraction/results/ledger.jsonl"
    out = ledger_path.parent / "summary.md"
    out.write_text(build_summary(ledger_path), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
